---
- name: Install etcd
  action: "{{ ansible_pkg_mgr }}"
  args:
        name: etcd
        state: latest
  notify:
    - restart etcd
  when: not is_atomic and ansible_distribution != "Ubuntu"

- name: Force etcd_source_type to github when packages are not available
  set_fact:
    etcd_source_type: "github-release"
  when: ansible_distribution == "Ubuntu"

- name: Install from github
  include: github-release.yml
  when: etcd_source_type == "github-release"
- name: OracleLinux | Install etcd
  yum:
    pkg=etcd
    state=latest
    enablerepo=virt7-testing
  notify:
    - restart etcd
  when: not is_atomic and ansible_distribution == "OracleLinux"

- name: Write etcd config file
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf
  notify:
    - restart etcd

- name: Write etcd systemd unit file for Debian
  copy: src=etcd.service dest=/etc/systemd/system
  notify:
    - reload systemd
    - restart etcd
  when: ansible_distribution == "Debian"

- name: Enable etcd
  service: name=etcd enabled=yes

- name: Start etcd
  service: name=etcd state=started
  register: etcd_started

- include: firewalld.yml
  when: has_firewalld

- include: iptables.yml
  when: not has_firewalld and has_iptables
