---
- name: Install flannel
  action: "{{ ansible_pkg_mgr }}"
  args:
        name: flannel
        state: latest
  when: not is_atomic and ansible_distribution != "OracleLinux"

- name: Install flannel | OracleLinux
  yum:
    pkg=flannel
    state=latest
    enablerepo=virt7-testing
  when: not is_atomic and ansible_distribution == "OracleLinux"

- name: Install Flannel config file
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld
  notify:
    - restart flannel

- name: Launch Flannel
  service: name=flanneld state=started enabled=yes
  notify:
    - restart flannel
